<!doctype html>
<html lang="en-gb" dir="ltr" class="uk-height-1-1">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="/">
        <title>Tiny Blog - sample application on Yen web-framework</title>
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

        <script src="vendor/jquery/jquery-2.2.1.min.js"></script>
        <script src="vendor/jquery/jquery.form.min.js"></script>

        <link rel="stylesheet" href="vendor/uikit/uikit.almost-flat.min.css">
        <link rel="stylesheet" href="vendor/uikit/notify.almost-flat.min.css">
        <script src="vendor/uikit/uikit.min.js"></script>
        <script src="vendor/uikit/notify.min.js"></script>

        <script src="scripts/page/auth.entrance.js"></script>
    </head>

    <body class="uk-height-1-1">

        <div class="uk-vertical-align uk-text-center uk-height-1-1">
            <div class="uk-vertical-align-middle" style="width: 250px;">

                <form class="uk-panel uk-panel-box uk-form" method="post" action="auth/signin" id="auth_form">
                    <div class="uk-form-row">
                        <input class="uk-width-1-1 uk-form-large" type="text" placeholder="Username" name="username" required>
                    </div>
                    <div class="uk-form-row">
                        <input class="uk-width-1-1 uk-form-large" type="password" placeholder="Password" name="password" required>
                    </div>
                    <div class="uk-form-row">
                        <button
                            class="uk-width-1-1 uk-button uk-button-primary uk-button-large"
                            type="submit" data-lbl="Sign In" data-wait="Please wait ...">
                            Sign In
                        </button>
                    </div>
                </form>

                <hr>

                <a href="auth/github/begin" class="uk-icon-hover uk-icon-github uk-icon-large" title="GitHub"></a>

            </div>
        </div>

    </body>

</html>
