<form class="uk-form uk-form-stacked" method="post" action="article/<?= $action ?>" id="article_form">
    <?= $csrf_guard ?>

    <input type="hidden" name="article_id" value="<?= $article->id() ?>">

    <div class="uk-form-row">
        <input type="text" name="title" placeholder="Article title" class="uk-width-1-1" required value="<?= $this->escape($article->title()) ?>">
    </div>

    <div class="uk-form-row">
        <textarea name="body" class="uk-width-1-1" rows="30" data-uk-htmleditor="{markdown:true}"><?= $this->escape($article->body()->source()) ?></textarea>
    </div>

    <div class="uk-form-row uk-text-center">
        <button type="button" class="uk-button uk-width-1-6" data-cancel>Cancel</button>
        <button type="submit" class="uk-button uk-button-primary uk-width-1-6">Save</button>
    </div>

</form>
